import { Box } from "@mui/material"
import Navbar from "@/components/Navbar"
import Head from "next/head"
import Sidebar from "@/components/Sidebar"

type LayoutProps = {
  children?: React.ReactNode
}

const DefaultLayout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Youtube Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ backgroundColor: "#0f0f0f" }}>
          <Navbar />
          <main>{children}</main>
        </Box>
      </main>
    </>
  )
}

export default DefaultLayout
